const Router = require('koa-router')
const Controller = require('./controller')

const app = new Router()

app.get('/widget', Controller.getTopicWidgetList)
app.get('/thumb', Controller.getTopicThumbList)
app.get('/count/:domain', Controller.getTopicCounts)
app.get('/boardLevel/:domain', Controller.getBoardLevel)
app.get('/categories/:domain', Controller.getCategories)
app.get('/read/:id', Controller.getContent)
app.get('/save', Controller.getSavedContent)
app.post('/list', Controller.getTopics)
app.post('/list/widget', Controller.getListToWidget)
app.post('/list/post', Controller.getPosts)
app.post('/list/post/me', Controller.getMyPosts)
app.post('/list/image', Controller.getImages)
app.post('/write', Controller.createTopic)
app.post('/write/save', Controller.createTopicSave)
app.post('/write/post', Controller.createPost)
app.post('/vote', Controller.createTopicVotes)
app.patch('/edit/notice', Controller.updateTopicByIsNotice)
app.patch('/edit/post', Controller.updatePost)
app.patch('/edit/:id', Controller.updateTopic)
app.delete('/delete', Controller.deleteTopic)
app.delete('/delete/post', Controller.deletePost)

module.exports = app
